name: Update Chinese EPG File

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: set variables
        run: |
          echo "UPDATE_TIME=$(date +%Y-%m-%d\ %H:%M)" >> $GITHUB_ENV

      - name: set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: prepare release
        uses: actions/checkout@v2
        with: 
          path: release
          ref: master

      - name: prepare generater
        uses: actions/checkout@v2
        with: 
          repository: BurningC4/getepg
          ssh-key: ${{ secrets.GETEPG }}
          path: getepg
          ref: main

      - name: get new epg file
        run: |
          sudo pip3 install -r getepg/requirements.txt
          sudo python3 getepg/getepg.py --file release/guide.xml
      - name: push release
        run: |
          git -C release config --local user.name github-actions
          git -C release config --local user.email github-actions@github.com
          git -C release add guide.xml
          git -C release commit -m "auto update at ${{ env.UPDATE_TIME }}"
          git -C release push --force >/dev/null 2>&1
